// lib/prompts.ts
// lib/prompts.ts
// Copied from src/prompts.ts to provide a server-safe copy used by API routes.

// Module definitions with 10 prompts each. These replicate the initial 12 modules.
const M1 = [
  {title:"Instagram Ad Copy Generator",quick:"Write 3 Instagram ad copy variations for [describe your listing, event, or agent brand]. Include a strong hook, value proposition, and call-to-action. Suggest 5 hashtags.", role:"ad copywriter",deliverable:"3 Instagram ad copy options + 5 hashtags",success:"CTR ≥2.5%; CPM <$[target]."},
  {title:"90-Day Inbound Lead Blueprint",quick:"Act as a marketing strategist for [type your city and state where you work - example: Austin, TX or Miami, FL]. Build a 90-day plan to get [tell me which type: buyer leads, seller leads, or investor leads] using [which platform will you focus on - example: Facebook Ads, Instagram Reels, or YouTube]. Include weekly calendar, KPIs, 5 hooks, UTMs.", role:"marketing strategist",deliverable:"A 12-week marketing calendar + 5 ready-to-use post ideas + tracking setup",success:"≥15 leads/week by week 6; CPL <$[your target cost per lead]."},
  {title:"YouTube Channel Plan (12 Episodes)",quick:"Design a 12-episode YouTube plan for [who are you trying to reach - example: first-time home buyers, people selling luxury homes, or real estate investors] in [type your city and state - example: Austin, TX or Seattle, WA]: titles, hooks, CTAs, b-roll, keywords. Include upload cadence + thumbnail angles.", role:"content strategist",deliverable:"12 video titles + scripts + thumbnail ideas + keywords for each episode",success:"≥5% CTR; Avg view duration ≥40%."},
  {title:"Local SEO Starter Kit",quick:"Create a local SEO checklist for [type your city and state - example: Austin, TX or Portland, OR]: GMB, citations, review cadence, FAQ schema, location pages. Output priorities + timelines.", role:"SEO consultant",deliverable:"Step-by-step checklist to get your Google ranking up",success:"Rank top-3 for [service + city] within 90 days (leading indicators)."},
  {title:"Listing Lead Magnet Funnel",quick:"Draft a 'Home Valuation + Market Update' funnel with landing copy, 3-email nurture, SMS, and retargeting angles.", role:"funnel architect",deliverable:"Landing page copy + 3 follow-up emails + 2 text messages",success:"Opt-in ≥25%; reply ≥15% by Day 7."},
  {title:"Neighborhood Guide Generator",quick:"Produce a neighborhood guide template for [which neighborhood do you specialize in - example: South Austin, Tarrytown, or Mueller]: lifestyle, schools, commute, pricing, 5 hotspots, map idea.", role:"local content creator",deliverable:"A complete neighborhood guide you can brand and share",success:"Guide downloads ≥50/month."},
  {title:"Open House Promo Pack",quick:"Create pre/during/post open house assets: IG reel script, flyer copy, sign-in CTA, follow-up text/email.", role:"event marketer",deliverable:"Social post scripts + flyer copy + follow-up messages",success:"CRM capture rate ≥30% of visitors."},
  {title:"Referral Engine Email Series",quick:"Write a 4-email series asking your sphere of influence (past clients, friends, family) for referrals and introductions: value first, social proof, soft ask, reminder.", role:"copywriter",deliverable:"4 emails asking for referrals (the right way)",success:"Reply rate ≥12%; referrals per 100 ≥5."},
  {title:"Instagram Reels Calendar (30 Days)",quick:"Build a 30-day Reels plan: hooks, captions, on-screen beats, CTAs. Balance education/story/listings.", role:"short-form coach",deliverable:"30 days of Instagram Reel ideas with captions",success:"3 posts/week; avg reach ↑ 50% in 30 days."},
  {title:"Brand Positioning Statement",quick:"Craft a unique positioning statement and tagline for [who do you mainly work with - example: first-time home buyers, people selling luxury condos, or real estate investors] in [type your city and state - example: Austin, TX or Denver, CO] with proof points and voice guide.", role:"brand strategist",deliverable:"Your unique tagline + 3 reasons why clients should choose you",success:"Message used consistently across site/social."},
  {title:"Review & Social Proof System",quick:"Design a post-closing review capture flow: ask script, links, reminder cadence, showcase placements.", role:"reputation manager",deliverable:"Scripts + reminders + plan to get more 5-star reviews",success:"≥70% of closed clients leave a review."}
];

const M2 = [
  {title:"Weekly Time Blocking Planner",quick:"Create a weekly time-blocking plan for [how many agents - example: just yourself, 3 agents, or 10 agents] in [your city/state]. Include prospecting, admin, client service, learning, and personal time. Output as a table.",role:"productivity planner",deliverable:"Weekly time-blocking table for agents",success:"≥80% time spent on high-ROI activities."},
  {title:"Weekly Productivity Audit",quick:"Audit calendar/tasks for a team of [how many agents are on your team - example: just yourself, 3 agents, 5 agents, or 10 agents] in [type your city and state - example: Austin, TX or Miami, FL]. Table: Task | Time | ROI | Automate/Delegate/Delete | Tool.",role:"productivity coach",deliverable:"A breakdown of what to stop doing, automate, or delegate",success:"Reclaim ≥5 hours/agent/week."},
  {title:"Daily Checklist Builder",quick:"Create a 12-task daily checklist balancing pipeline/admin/prospecting/learning. Export-friendly.",role:"workflow architect",deliverable:"Your daily to-do list (morning, afternoon, evening)",success:"≥80% daily completion."},
  {title:"Pipeline SOP (Lead→Close)",quick:"Define CRM stages, entry/exit criteria, tasks, SLAs, and 2 automations/stage.",role:"contact database consultant",deliverable:"Step-by-step process from lead to closed deal",success:"response time compliance ≥95%."},
  {title:"Listing Launch Timeline (T-14→T+14)",quick:"Create a listing launch Gantt with owners, assets, dependencies, compliance checks.",role:"project manager",deliverable:"28-day timeline showing what to do and when",success:"0 missed disclosures; on-time go-live."},
  {title:"Buyer Onboarding Journey",quick:"Map onboarding for [describe the buyers you typically work with - example: first-time buyers under 35, people downsizing from big homes, or real estate investors]: welcome pack, expectations, template updates.",role:"CX designer",deliverable:"Welcome email + what to send buyers on day 1, 7, 14",success:"Buyer satisfaction score ≥9/10."},
  {title:"Vendor Directory Framework",quick:"Sheet structure for lenders/inspectors/trades with verification cadence and disclaimers.",role:"ops manager",deliverable:"Spreadsheet template to organize your vendors",success:"Quarterly verification 100%."},
  {title:"File Naming & Docs Policy",quick:"Create naming convention + folder tree + retention schedule for [which cloud storage do you use - example: Google Drive, Dropbox, OneDrive, or iCloud].",role:"compliance officer",deliverable:"Simple system to name and organize your files",success:"Doc retrieval <2 minutes."},
  {title:"Inbox & DM Triage SOP",quick:"Multi-channel response time + templates + escalation path; rules for auto-labels/tasks.",role:"communication lead",deliverable:"Rules for responding to emails and DMs fast",success:"Avg response <15 min; 0 missed leads."},
  {title:"Post-Closing Handoff Process",quick:"Checklist to TC: survey, review ask, gift, anniversary automation.",role:"transaction coordinator",deliverable:"Post-close checklist (survey, gift, review request)",success:"100% clients enter nurture."},
  {title:"One-Page Operating System",quick:"Create a 1-pager: Vision, 90-day goals, goal metrics, meeting rhythm, org chart.",role:"business coach",deliverable:"Your business on one page (goals, metrics, meetings)",success:"<30 min weekly meeting, goal metric alignment."}
];

const M3 = [
  {title:"Quarterly Business Review Framework",quick:"Design a quarterly business review template for agents. Include sections for goals, metrics, wins, challenges, and next steps. Output as a fillable worksheet.",role:"business strategist",deliverable:"Quarterly review worksheet for agents",success:"≥2 new strategies implemented per quarter."},
  {title:"GCI Reverse-Engineering",quick:"Calculate how to hit your income goal: [what's your annual income goal - example: $150,000, $250,000, or $500,000] with an average commission per deal of [what do you typically make per transaction - example: $5,000, $8,000, or $12,000]. Get weekly activity targets using conversion rates.",role:"performance coach",deliverable:"Exact number of calls and appointments you need each week",success:"Exact # calls/appts to hit target."},
  {title:"Weekly Scorecard",quick:"Scorecard for leading/lagging: calls, contacts, appts, contracts, posts.",role:"ops analyst",deliverable:"One-page scorecard to track your weekly numbers",success:"Update in <5 min weekly."},
  {title:"Prospecting Habit Protocol",quick:"Build a 20-minute daily prospecting ritual for [how do you find new clients - example: knocking on doors, calling expired listings, sending DMs on social media, or sending emails]: trigger→routine→reward.",role:"behavioral coach",deliverable:"Simple daily routine to build a prospecting habit",success:"≥5 new contacts/day × 21 days."},
  {title:"Weekly Reflection Template",quick:"One-page review: wins, numbers, blockers, experiments, focus.",role:"growth mentor",deliverable:"Weekly check-in template (wins, numbers, what to fix)",success:"Consistent self-reporting trends."},
  {title:"30-Day Skill Sprint",quick:"Design a 30-day sprint to master [which skill do you want to improve - example: making cold calls, creating social media content, giving listing presentations, or negotiating deals]: daily drills + checkpoints.",role:"training manager",deliverable:"30-day plan to master one skill (with daily practice)",success:"≥20% competence gain."},
  {title:"Goal Red-Team Exercise",quick:"List all the reasons you might miss [what's your big goal this year - example: closing 50 transactions, earning $250K in commissions, or signing 100 new clients] and create a plan to prevent each one.",role:"strategic coach",deliverable:"What could go wrong with your goal + how to prevent it",success:"2 preventions implemented now."},
  {title:"Accountability Partner Rules",quick:"Create a 15-min weekly accountability agenda + commitment contract.",role:"team coach",deliverable:"Weekly check-in agenda for you and your accountability partner",success:"≥80% completion in 4 weeks."},
  {title:"Personal P&L Dashboard",quick:"Agent P&L: income, taxes, savings, investments; alerts <40% margin.",role:"financial coach",deliverable:"Simple profit tracker (what you make vs. what you keep)",success:"Know net profit weekly."},
  {title:"Morning Priming Prompts",quick:"3-min exercise: affirmation, visualization, gratitude, micro-goal.",role:"mindset coach",deliverable:"3-minute morning routine to start your day right",success:"Mood/energy ≥8/10 after 7 days."},
  {title:"End-of-Day Debrief",quick:"Nightly check-in: what mattered, improvements, top win; auto-log.",role:"reflection facilitator",deliverable:"Quick end-of-day journal prompts (3 questions)",success:"≥70% completion in 30 days."}
];

const M4 = [
  {title:"Luxury Listing Checklist",quick:"Create a step-by-step checklist for preparing, marketing, and selling a luxury property in [your city/state]. Include staging, photography, marketing channels, compliance, and client communication.",role:"luxury listing specialist",deliverable:"Luxury listing prep and marketing checklist",success:"Sold at/above list price in ≤45 days."},
  {title:"Listing Description That Converts",quick:"Write a compelling listing description for [what type of property is this - example: 3-bedroom single-family home, 2-bed downtown condo, or new-build townhome] located at [what is the full property address - example: 1234 Oak Ridge Drive] in [type your city and state - example: Austin, TX or Denver, CO]. Highlight [name 3 standout features - example: chef kitchen, rooftop deck, energy-efficient windows], include lifestyle hooks, fair housing–compliant language, and a strong call-to-action.",role:"listing copy specialist",deliverable:"Headline + 180–300 word description + 3 CTA variations + 8–12 hashtag suggestions",success:"≥3 qualified inquiries in first 7 days."},
  {title:"Pricing Strategy Script",quick:"Price talk track with comps, DOM, trends; analogy→data→position→CTA.",role:"listing-presentation coach",deliverable:"Script to explain pricing to sellers (with market data)",success:"Seller accepts within 5%."},
  {title:"Commission Value Conversation",quick:"Handle ‘lower your commission’: acknowledge→value reframe→choice close.",role:"negotiation coach",deliverable:"How to respond when sellers ask you to lower your fee",success:"≥70% full fee retention."},
  {title:"FSBO Conversion Sequence",quick:"Create 3 phone calls and 3 text messages to convert a for-sale-by-owner seller. Their situation: [describe their situation - example: going through a divorce and need to sell in 60 days, inherited a property and want a quick sale, or downsizing and flexible on timing]. Use compliant, professional language.",role:"lead-conversion specialist",deliverable:"Call and text scripts to convert for-sale-by-owner sellers",success:"≥20% appointment rate."},
  {title:"Competing Agent Response",quick:"Acknowledge multi-agent interviews; differentiate→proof→low-risk CTA.",role:"persuasion coach",deliverable:"What to say when sellers are interviewing other agents",success:"≥50% signed listing."},
  {title:"Rate-Sensitivity Buyer Talk",quick:"Explain payment impact; discuss buy-downs/refi-later with disclaimer.",role:"mortgage conversationalist",deliverable:"How to talk to buyers worried about interest rates",success:"≥70% remain active."},
  {title:"Multiple-Offer Strategy",quick:"Buyer plan: prep, terms, escalation, appraisal gap, debrief.",role:"buyer strategist",deliverable:"Strategy for winning in multiple-offer situations",success:"Win rate ≥60% multi-offer."},
  {title:"Buyer Consult Deck Outline",quick:"Slide outline: process, timeline, stats, agency, next steps.",role:"training designer",deliverable:"Slide outline for your buyer consultation meeting",success:"≥90% to signed agency."},
  {title:"Listing Refresh Plan",quick:"Your listing has been on the market for [how many days - example: 21 days, 30 days, 45 days, or 60 days] with low activity. Create a relaunch plan: reshoot photos, rewrite description, retarget ads, adjust price, relaunch campaign.",role:"marketing consultant",deliverable:"Plan to revive a stale listing (new photos, price, ads)",success:"Showings ↑ ≥30% in 7 days."},
  {title:"Graceful Disengagement Scripts",quick:"5 ways to exit misaligned clients while preserving goodwill.",role:"relationship strategist",deliverable:"5 polite ways to fire a difficult client",success:"Positive reviews maintained."},
  {title:"Repair Request Negotiation",quick:"Matrix for inspection items; fix/credit/price + sample email.",role:"contract coach",deliverable:"How to negotiate repairs after inspection",success:"≥80% accepted w/o large cuts."}
];

const M5 = [
  {title:"Client Onboarding Welcome Kit",quick:"Create a welcome kit for new clients (buyers or sellers) including a personalized welcome email, checklist, FAQ, and intro video script. Output as a ready-to-send package.",role:"client onboarding specialist",deliverable:"Welcome kit: email, checklist, FAQ, video script",success:"Client satisfaction ≥9/10 in first week."},
  {title:"White-Glove Onboarding",quick:"3 touches in 72h: welcome, next-7-days checklist, FAQ video.",role:"CX designer",deliverable:"Welcome email + 7-day checklist + FAQ video for new clients",success:"Week-1 CSAT ≥9/10."},
  {title:"Weekly Update Cadence",quick:"Email + text summary + CRM log: progress, next steps, key dates.",role:"communications strategist",deliverable:"Weekly update template (progress, next steps, key dates)",success:"0 status-check inquiries."},
  {title:"Bad-News Playbook",quick:"Scripts for appraisal shortfall/inspection issues: acknowledge→facts→options→next step.",role:"crisis comms coach",deliverable:"Scripts for delivering bad news (appraisal low, inspection issues)",success:"≥90% stay engaged."},
  {title:"Move-Day Concierge",quick:"Checklist: utilities, vendors, locksmith, mail, welcome kit + 7/30/90 surveys.",role:"service planner",deliverable:"Moving day checklist + welcome kit + follow-up surveys",success:"≥80% survey response; ≥1 referral in 6 mo."},
  {title:"Expectations Agreement",quick:"Agreement: communication hours, response times, decision rights.",role:"client-relations consultant",deliverable:"Client agreement (communication hours, response times)",success:"0 major comms breakdowns."},
  {title:"Year-1 Maintenance Series",quick:"Create quarterly maintenance reminder emails for homeowners with [what type of property and weather - example: single-family homes in hot Texas summers, condos in humid Florida, or houses with snowy Colorado winters]. Include vendor recommendations.",role:"nurture specialist",deliverable:"4 seasonal maintenance emails for homeowners",success:"Open ≥40%; click ≥10%."},
  {title:"Vendor Issue Escalation",quick:"Flow: client→agent→vendor→broker→legal; logging + timeline.",role:"risk manager",deliverable:"Process when vendors mess up (who to contact, timeline)",success:"Ack <24h; resolve <72h."},
  {title:"Surprise & Delight Moments",quick:"Plan 5 thoughtful touchpoints at key milestones. Budget per client: [how much do you spend on client gifts - example: $50, $100, or $250]. Include personalization ideas.",role:"retention strategist",deliverable:"5 gift ideas for client milestones",success:"Referrals ↑ ≥20% YoY."},
  {title:"Service Recovery Templates",quick:"Apology|Accountability|Remedy|Re-commit|Follow-up + public-review reply.",role:"reputation consultant",deliverable:"Apology templates + how to fix client complaints",success:"Complaints closed; ≥4★ avg."},
  {title:"Closing-Day Story Pack",quick:"Shot list, captions, hashtags, review ask + compliance note.",role:"social content coach",deliverable:"Shot list + captions + hashtags for closing day posts",success:"≥70% clients post/tag in 24h."}
];

const M6 = [
  {title:"Marketing ROI Calculator",quick:"Calculate the ROI for your marketing campaigns. Input: budget, leads generated, deals closed, average commission. Output: ROI %, cost per lead, cost per deal.",role:"ROI analyst",deliverable:"Marketing ROI calculator for agents",success:"ROI ≥20% per campaign."},
  {title:"12-Month Cashflow Model",quick:"Forecast income/expenses with tax, reserves, profit targets; monthly table.",role:"finance coach",deliverable:"Monthly income and expense tracker",success:"Know runway & savings by month 12."},
  {title:"Marketing Budget Allocator",quick:"Split your monthly marketing budget of [how much per month - example: $1,000, $2,500, or $5,000] across [which platforms do you advertise on - example: Facebook Ads, Google Ads, Zillow leads, or direct mail]. Include cost-per-lead targets and rules for scaling winners or cutting losers.",role:"marketing CFO",deliverable:"How to split your marketing budget across channels",success:"≤$[Y] CPL; ≥20% ROI/channel."},
  {title:"Profitability Review Audit",quick:"Analyze expenses by ROI; keep/cut/renegotiate + 90-day savings plan.",role:"business consultant",deliverable:"Which expenses to cut + 90-day savings plan",success:"Reduce expenses ≥15%."},
  {title:"Commission Advance Tree",quick:"Decision framework: cashflow, deal certainty, cost, alternatives.",role:"risk advisor",deliverable:"When to take a commission advance (decision tree)",success:"0 unnecessary advances."},
  {title:"Team Compensation Plan",quick:"Comp for ISA/LA/TC: base/split/bonus/cap + retention incentives.",role:"comp architect",deliverable:"Pay structure for assistants and coordinators",success:"Turnover <10% annually."},
  {title:"Quarterly Tax Planning",quick:"Checklist: estimates, deductions log, retirement, receipts; reminders.",role:"tax strategy coach",deliverable:"Tax checklist + deductions + quarterly payment reminders",success:"100% on-time payments."},
  {title:"Investor Service Line",quick:"Offering for investors: criteria, underwriting sheet, fees, deck.",role:"business developer",deliverable:"Service offering for real estate investors",success:"Launch in ≤45 days."},
  {title:"Market Analytics Template",quick:"Create a market statistics dashboard for [describe your specific market - example: downtown Austin condos, suburban single-family homes in Plano, or luxury estates in Scottsdale]. Include sale-to-list price ratios, days on market, months of inventory, and talking points.",role:"data analyst",deliverable:"Market stats dashboard with talking points",success:"Monthly update informs listings."},
  {title:"Vendor RFP Generator",quick:"RFP template: scope, deliverables, metrics, pricing, rubric.",role:"procurement advisor",deliverable:"Request for proposal template for vendors",success:"Clarity pre-contract."},
  {title:"Insurance & Risk Checklist",quick:"Policies: E&O, cyber, GL, data; renewal dates; claims protocol.",role:"risk manager",deliverable:"Insurance policies you need + renewal tracker",success:"0 coverage gaps; on-time renewals."}
];

const M7 = [
  {title:"Appraisal Gap Negotiation Script",quick:"Create a negotiation script for handling appraisal gaps (when the appraisal comes in below contract price). Include talking points for buyers and sellers, options for bridging the gap, and compliance reminders.",role:"negotiation strategist",deliverable:"Appraisal gap negotiation script for agents",success:"≥80% gap resolved without contract cancellation."},
  {title:"BATNA Power Map",quick:"Build your backup plan (BATNA) for this negotiation: [describe the situation - example: appraisal came in $15k low, buyer wants $10k in seller credits, or you're dealing with multiple offers]. Include risk assessment.",role:"negotiation coach",deliverable:"Backup options if this deal falls through",success:"≥2 creative options + thresholds."},
  {title:"Concession Strategy Ladder",quick:"Rank tradeables by cost to client vs value to other party.",role:"deal architect",deliverable:"What to give up and what to ask for in return",success:"≥50% concessions offset."},
  {title:"Anchoring Language Framework",quick:"3 anchors: data-first, emotional story, bracketed range; phrases to avoid.",role:"persuasive linguist",deliverable:"How to set price expectations with words",success:"Offers land within 3% target."},
  {title:"Calibrated Question Builder",quick:"10 ‘how/what’ questions + labels to uncover constraints.",role:"Voss-style trainer",deliverable:"10 questions to uncover what the other side really wants",success:"≥50% more info disclosed."},
  {title:"Appraisal Gap Plan",quick:"The appraisal came in low by [how much - example: $5,000, $10,000, or $15,000]. Create a plan with these options: challenge the appraisal, adjust the price, find cash to bridge the gap, renegotiate terms, or cancel the contract.",role:"transaction strategist",deliverable:"What to do when appraisal comes in low",success:"≥70% resolved w/o cancel."},
  {title:"Inspection Resolution Matrix",quick:"Minor/major matrix: repair/credit/ignore with suggested language.",role:"mediator",deliverable:"How to handle inspection items (repair, credit, or ignore)",success:"≥90% resolution in 3 days."},
  {title:"Deadline Pressure Playbook",quick:"Resist TILI deadlines: scripts, alternatives, reframes; pre-deadline checklist.",role:"time-based tactician",deliverable:"How to handle artificial deadlines",success:"0 rushed concessions."},
  {title:"Deal Rescue Protocol",quick:"Save deals with financing/inspection/cold-feet issues; flow + scripts.",role:"conflict specialist",deliverable:"How to save deals that are falling apart",success:"≥60% revived."},
  {title:"Multiple-Offer Ethics Guide",quick:"Create ethical scripts and procedures for handling multiple offers according to [your state or brokerage rules - example: Texas TREC regulations, California DRE requirements, Keller Williams policy, or eXp Realty guidelines]. Include disclosure requirements and offer management.",role:"compliance advisor",deliverable:"How to handle multiple offers ethically and legally",success:"100% compliance; 0 complaints."},
  {title:"Negotiation Post-Mortem",quick:"Debrief: what worked, surprises, missed clues, system change; rubric.",role:"reflective coach",deliverable:"Review template after each negotiation",success:"Complete within 48h of close."}
];

const M8 = [
  {title:"Relocation Brief",quick:"Create a relocation brief for buyers moving to [your city/state]. Include schools, commute, rent vs buy, neighborhoods, and local tips. Output as a welcome pack.",role:"relocation advisor",deliverable:"Relocation welcome pack for buyers",success:"Client shortlists 3 areas within 48h."},
  {title:"Needs-Match Matrix",quick:"Create a must-have versus nice-to-have matrix for [describe your client - example: first-time buyers with a $300K budget, move-up buyers needing more space, or downsizers going from house to condo] in [type your city and state - example: Austin, TX or Portland, OR]. Include commute preferences.",role:"profiling strategist",deliverable:"Weighted table with fit scores.",success:"≥3 neighborhoods fit ≥80%."},
  {title:"Smart Search Strings",quick:"Create MLS and portal search strings with alerts for [what is your buyer looking for - example: 3 bedroom 2 bath under $400K with a pool in the 78704 zip code, new construction 4 bedroom homes in top-rated school districts, or waterfront condos under $600K]. Set up across MLS, Zillow, and Redfin.",role:"portal power-user",deliverable:"Search filters to find exactly what buyers want",success:"≤3 irrelevant listings/week."},
  {title:"Off-Market Outreach",quick:"Write letters, emails, and text messages to find off-market properties in [describe your target - example: single-family homes in the Westlake neighborhood, luxury condos in downtown, or investment properties in East Austin]. Include legally compliant language and opt-out instructions.",role:"listing acquisition specialist",deliverable:"Letters and emails to find off-market properties",success:"≥5% response / 100 sends."},
  {title:"New-Build vs Resale",quick:"Side-by-side with lifecycle cost + agent talking points.",role:"buyer educator",deliverable:"Side-by-side comparison for buyers",success:"Client chooses confidently."},
  {title:"Lender Options Explainer",quick:"Compare different lenders and loan programs for a buyer with [describe their financial situation - example: 720 credit score earning $80K per year, 650 credit score earning $120K per year, or 780 credit score earning $55K per year]. Show pros and cons of each option.",role:"financing translator",deliverable:"How to compare lenders and loan programs",success:"Select 2 qualified options in 48h."},
  {title:"Investor Deal Screener",quick:"Create a quick screening tool for [what's your investment strategy - example: buying properties to flip and resell, buying rentals to hold long-term, or using the BRRRR method to refinance after rehab]. Calculate cap rate, cash-on-cash return, and debt service coverage ratio.",role:"underwriting coach",deliverable:"Quick calculator for investment properties",success:"Shortlist in under 10 minutes."},
  {title:"Relocation Brief",quick:"Relocation pack: schools, commute, rents vs buys, neighborhoods.",role:"relocation advisor",deliverable:"Welcome pack for buyers moving to your area",success:"Client shortlists 3 areas."},
  {title:"School-Zone Navigator",quick:"Create a school-focused search guide for [describe the family - example: a couple with 2 elementary-age kids, a single parent with one teenager, or a young family planning for future children]. Include school ratings, attendance zones, and property taxes.",role:"family move strategist",deliverable:"How to search by school ratings and zones",success:"Confidence in top 2 zones."},
  {title:"Downsizer Options Map",quick:"Condos/townhomes w/ accessibility, HOA insights, budgets.",role:"downsizing consultant",deliverable:"Condo and townhome options for downsizers",success:"Tour list within 48h."},
  {title:"First-Time Buyer Roadmap",quick:"From pre-approval to close with expectation management scripts.",role:"first-time coach",deliverable:"Step-by-step timeline from pre-approval to closing",success:"On-track milestones each week."}
];

const M9 = [
  {title:"Referral Request Script",quick:"Write a script for requesting referrals from past clients after a successful closing. Include email, text, and phone call variations. Make it friendly, professional, and easy to personalize.",role:"referral specialist",deliverable:"Referral request scripts (email, text, call)",success:"≥20% response rate within 30 days."},
  {title:"12-Touch Sphere Plan",quick:"Create a monthly outreach plan for your sphere of influence (past clients, friends, family, and vendors). Include the right channel, theme, and call-to-action for each touchpoint.",role:"retention strategist",deliverable:"Monthly outreach plan for past clients and sphere",success:"≥30% engagement/touch."},
  {title:"Home-Anniversary Automation",quick:"CRM workflow: reminder→gift tier [$25/$50/$100]→message→social post.",role:"automation expert",deliverable:"Automated anniversary messages + gift tiers",success:"≥95% anniversaries auto-celebrated."},
  {title:"Community Spotlight Series",quick:"Plan 12 social media posts featuring local businesses, nonprofits, and community events in [which neighborhood are you focusing on - example: Tarrytown in Austin, Hyde Park in Austin, or Westlake Hills].",role:"local content creator",deliverable:"12 posts featuring local businesses",success:"+25% local followers; 3 collabs."},
  {title:"Client-Appreciation Event",quick:"Plan a client appreciation event. What kind: [describe your event - example: a summer BBQ, holiday cocktail party, spring garden tour, or fall tailgate party]. Include timeline, vendors, sponsors, and RSVP system.",role:"event marketer",deliverable:"Event planning checklist (venue, vendors, invites)",success:"≥60% attendance; ≥3 referrals."},
  {title:"Review-to-Referral Bridge",quick:"Turn 5★ reviews into warm referral asks (text/email/DM).",role:"relationship copywriter",deliverable:"How to turn 5-star reviews into referral requests",success:"≥20% provide a referral in 30 days."},
  {title:"Newsletter Engine",quick:"Monthly template: market stat, story, tip, local pick, CTA.",role:"newsletter editor",deliverable:"Monthly newsletter template (market stats + tips + local picks)",success:"Open ≥35%, click ≥6%."}
];

// Truncated: M10, M11, M12 omitted for brevity. Add full modules if needed.

export const prompts = [M1, M2, M3, M4, M5, M6, M7, M8, M9];
