// src/labelOverrides.ts
export type LabelOverride = { match: string; title: string; subtitle: string };

export const labelOverrides: Record<string, LabelOverride[]> = {
  "Module 1 — Lead Generation & Marketing": [
    { match: "90-Day Inbound Lead Blueprint", title: "Get More Leads in 90 Days", subtitle: "12-week inbound plan with weekly KPIs, hooks, and UTMs." },
    { match: "YouTube Channel Plan (12 Episodes)", title: "Plan 12 YouTube Videos", subtitle: "Titles, hooks, CTAs, keywords, b-roll, thumbnail angles." },
    { match: "Local SEO Starter Kit", title: "Rank Locally on Google", subtitle: "GMB setup, citations, reviews, schema, and location pages." },
    { match: "Listing Lead Magnet Funnel", title: "Capture Listing Leads", subtitle: "Home-value funnel page + 3-email nurture + SMS follow-up." },
    { match: "Neighborhood Guide Generator", title: "Create Neighborhood Guide", subtitle: "Lifestyle, schools, commute, pricing, hotspots, and map ideas." },
    { match: "Open House Promo Pack", title: "Boost Open House Traffic", subtitle: "IG reel script, flyer copy, sign-in CTA, and follow-up." },
    { match: "Referral Engine Email Series", title: "Get More Referrals", subtitle: "4-email SOI series: value, proof, soft ask, reminder." },
    { match: "Instagram Reels Calendar (30 Days)", title: "Grow on Instagram", subtitle: "30-day Reels plan: hooks, captions, on-screen beats, CTAs." },
    { match: "Brand Positioning Statement", title: "Sharpen Your Positioning", subtitle: "Unique niche + tagline + 3 proof points + tone guide." },
    { match: "Review & Social Proof System", title: "Collect More Reviews", subtitle: "Post-closing asks, cadence, reminders, and showcase placements." },
  ],

  "Module 2 — Operations & Time Management": [
    { match: "Weekly Productivity Audit", title: "Win Back 5 Hours/Week", subtitle: "Calendar/task audit with ROI and automate/delegate rules." },
    { match: "Daily Checklist Builder", title: "Daily Agent Checklist", subtitle: "AM/Mid/PM tasks with durations—export-ready." },
    { match: "Pipeline SOP (Lead→Close)", title: "Standardize Your Pipeline", subtitle: "CRM stages, entry/exit criteria, SLAs, and automation." },
    { match: "Listing Launch Timeline (T-14→T+14)", title: "On-Time Listing Launch", subtitle: "Gantt timeline, owners, assets, dependencies, compliance." },
    { match: "Buyer Onboarding Journey", title: "Delight New Buyers", subtitle: "Welcome pack, expectations, and update templates." },
    { match: "Vendor Directory Framework", title: "Pro Vendor Directory", subtitle: "Lenders/inspectors/trades with verification cadence." },
    { match: "File Naming & Docs Policy", title: "Organize Your Files", subtitle: "Naming, folder tree, retention schedule for your drive." },
    { match: "Inbox & DM Triage SOP", title: "Never Miss a Lead", subtitle: "SLAs, templates, auto-labels, and task rules." },
    { match: "Post-Closing Handoff Process", title: "Seamless Post-Closing", subtitle: "TC checklist, survey, review ask, gifts, anniversary." },
    { match: "One-Page Operating System", title: "Your Business on 1 Page", subtitle: "Vision, 90-day goals, KPIs, cadence, org chart." },
  ],

  "Module 3 — Goal Setting & Accountability": [
    { match: "GCI Reverse-Engineering", title: "Hit Your GCI Target", subtitle: "Convert goals into weekly activity targets that add up." },
    { match: "Weekly Scorecard", title: "Track What Matters", subtitle: "Leading/lagging KPIs: calls, appts, contracts, posts." },
    { match: "Prospecting Habit Protocol", title: "Daily Prospecting Habit", subtitle: "20-minute ritual with trigger → routine → reward." },
    { match: "Weekly Reflection Template", title: "Weekly Review Ritual", subtitle: "Wins, numbers, blockers, experiments, focus." },
    { match: "30-Day Skill Sprint", title: "Master a Skill in 30 Days", subtitle: "Daily drills + checkpoints for measurable progress." },
    { match: "Goal Red-Team Exercise", title: "Stress-Test Your Goals", subtitle: "List failure risks and create mitigations now." },
    { match: "Accountability Partner Rules", title: "Accountability That Works", subtitle: "15-min weekly agenda + commitment contract." },
    { match: "Personal P&L Dashboard", title: "Know Your Profit", subtitle: "Income, taxes, savings, alerts under 40% margin." },
    { match: "Morning Priming Prompts", title: "Start Days on Fire", subtitle: "Affirmation, visualization, gratitude, micro-goal." },
    { match: "End-of-Day Debrief", title: "Finish Strong Daily", subtitle: "Top win, improvements, and next-day focus." },
  ],

  "Module 4 — Listing & Buyer Presentations": [
    { match: "Pricing Strategy Script", title: "Win the Pricing Talk", subtitle: "Analogy → data → position → clear CTA." },
    { match: "Commission Value Conversation", title: "Defend Your Fee", subtitle: "Acknowledge, reframe value, choice-close scripts." },
    { match: "FSBO Conversion Sequence", title: "Convert FSBOs", subtitle: "3 calls + 3 texts with compliance-safe language." },
    { match: "Competing Agent Response", title: "Beat Multiple Agents", subtitle: "Differentiate → proof → low-risk CTA." },
    { match: "Rate-Sensitivity Buyer Talk", title: "Handle Rate Objections", subtitle: "Payment impact, buy-downs, refi-later disclosures." },
    { match: "Multiple-Offer Strategy", title: "Win Multiple Offers", subtitle: "Prep, terms, escalation, appraisal gap plan." },
    { match: "Buyer Consult Deck Outline", title: "Close Agency Agreements", subtitle: "Process, timeline, stats, agency, next steps." },
    { match: "Listing Refresh Plan", title: "Revive a Stale Listing", subtitle: "Reshoot, recopy, retarget, reprice, relaunch." },
    { match: "Graceful Disengagement Scripts", title: "Exit Bad Fits Kindly", subtitle: "5 scripts to end misaligned relationships." },
    { match: "Repair Request Negotiation", title: "Negotiate Repairs Smarter", subtitle: "Fix/credit/price matrix + sample email." },
  ],

  "Module 5 — Client Experience & Retention": [
    { match: "White-Glove Onboarding", title: "White-Glove Onboarding", subtitle: "3 touches in 72 hours with welcome, checklist, FAQ." },
    { match: "Weekly Update Cadence", title: "Send Weekly Updates", subtitle: "Email + text summary with key dates & next steps." },
    { match: "Bad-News Playbook", title: "Deliver Bad News Well", subtitle: "Acknowledge → facts → options → next step scripts." },
    { match: "Move-Day Concierge", title: "Be Their Concierge", subtitle: "Utilities, vendors, locksmith, mail, welcome kit." },
    { match: "Expectations Agreement", title: "Set Expectations Early", subtitle: "Hours, response times, decision rights agreement." },
    { match: "Year-1 Maintenance Series", title: "Stay Relevant All Year", subtitle: "Quarterly maintenance emails by property/climate." },
    { match: "Vendor Issue Escalation", title: "Escalate Vendor Issues", subtitle: "Client → agent → vendor → broker → legal flow." },
    { match: "Surprise & Delight Moments", title: "Delight at Milestones", subtitle: "5 budgeted touchpoints personalized to clients." },
    { match: "Service Recovery Templates", title: "Turn Mistakes Around", subtitle: "Apology, remedy, recommit, follow-up templates." },
    { match: "Closing-Day Story Pack", title: "Share Closing Stories", subtitle: "Shot list, captions, hashtags, review ask." },
  ],

  "Module 6 — Finance & Profitability": [
    { match: "12-Month Cashflow Model", title: "Forecast Cashflow", subtitle: "Income/expenses, tax, reserves, profit targets." },
    { match: "Marketing Budget Allocator", title: "Allocate Ad Budget", subtitle: "Distribute spend, set CPL targets, scale/cut rules." },
    { match: "Profitability Review Audit", title: "Cut Wasteful Spend", subtitle: "Expense analysis with keep/cut/renegotiate plan." },
    { match: "Commission Advance Tree", title: "Use Advances Wisely", subtitle: "Decision framework to avoid costly mistakes." },
    { match: "Team Compensation Plan", title: "Design Fair Comp", subtitle: "ISA/LA/TC splits, bonuses, caps, retention." },
    { match: "Quarterly Tax Planning", title: "Stay Tax-Ready", subtitle: "Estimates, deductions, retirement, receipts, reminders." },
    { match: "Investor Service Line", title: "Launch Investor Arm", subtitle: "Criteria, underwriting sheet, fees, simple deck." },
    { match: "Market Analytics Template", title: "Build Market Dashboard", subtitle: "SP/LP, DOM, MOI, $/sqft + talking points." },
    { match: "Vendor RFP Generator", title: "Run Better RFPs", subtitle: "Scope, deliverables, metrics, pricing, rubric." },
    { match: "Insurance & Risk Checklist", title: "Cover Your Risks", subtitle: "E&O, cyber, GL, renewals, claims protocol." },
  ],

  "Module 7 — Negotiation & Deal Strategy": [
    { match: "BATNA Power Map", title: "Know Your BATNA", subtitle: "Options, thresholds, risks laid out clearly." },
    { match: "Concession Strategy Ladder", title: "Trade Smarter", subtitle: "Rank concessions by cost vs value to them." },
    { match: "Anchoring Language Framework", title: "Anchor the Conversation", subtitle: "Data, story, and bracketed range anchors." },
    { match: "Calibrated Question Builder", title: "Ask Better Questions", subtitle: "10 ‘how/what’ questions that unlock info." },
    { match: "Appraisal Gap Plan", title: "Solve Appraisal Gaps", subtitle: "Rebuttal, reprice, bridge cash, renegotiate." },
    { match: "Inspection Resolution Matrix", title: "Resolve Inspections Fast", subtitle: "Minor/major matrix with suggested language." },
    { match: "Deadline Pressure Playbook", title: "Beat Deadline Pressure", subtitle: "Scripts & checklists to avoid rushed deals." },
    { match: "Deal Rescue Protocol", title: "Rescue Failing Deals", subtitle: "Paths for financing, inspection, cold feet." },
    { match: "Multiple-Offer Ethics Guide", title: "Stay Fully Compliant", subtitle: "Ethical offer handling scripts by state." },
    { match: "Negotiation Post-Mortem", title: "Level Up After Deals", subtitle: "Debrief what worked and fix systems." },
  ],

  "Module 8 — Buyer Journey & Search Tools": [
    { match: "Needs-Match Matrix", title: "Match Needs to Areas", subtitle: "Weighted matrix to pick the best neighborhoods." },
    { match: "Smart Search Strings", title: "Search Smarter Online", subtitle: "Boolean strings + alerts for MLS/portals." },
    { match: "Off-Market Outreach", title: "Find Off-Market Homes", subtitle: "Letter/email/text outreach with opt-out." },
    { match: "New-Build vs Resale", title: "New Build or Resale?", subtitle: "Side-by-side with lifecycle costs." },
    { match: "Lender Options Explainer", title: "Compare Lender Options", subtitle: "Programs explained by profile with pros/cons." },
    { match: "Investor Deal Screener", title: "Screen Investment Deals", subtitle: "Quick cap, cash-on-cash, and DSCR checks." },
    { match: "Relocation Brief", title: "Relocation Made Easy", subtitle: "Schools, commute, rent vs buy, neighborhoods." },
    { match: "School-Zone Navigator", title: "Navigate School Zones", subtitle: "Map, ratings, taxes, and talking points." },
    { match: "Downsizer Options Map", title: "Downsize with Confidence", subtitle: "Condos/townhomes with access & HOA notes." },
    { match: "First-Time Buyer Roadmap", title: "Guide First-Time Buyers", subtitle: "From pre-approval to close—expectations set." },
  ],

  "Module 9 — Sphere & Community Marketing": [
    { match: "12-Touch Sphere Plan", title: "Stay Top-of-Mind", subtitle: "12-month SOI plan by channel and CTA." },
    { match: "Home-Anniversary Automation", title: "Automate Anniversaries", subtitle: "Reminder → gift tiers → message → social." },
    { match: "Community Spotlight Series", title: "Spotlight Local Businesses", subtitle: "12-episode plan for community content." },
    { match: "Client-Appreciation Event", title: "Host Great Events", subtitle: "Timeline, vendors, sponsors, RSVP plan." },
    { match: "Review-to-Referral Bridge", title: "Turn Reviews to Referrals", subtitle: "Text/email/DM asks that convert." },
    { match: "Newsletter Engine", title: "Send a Better Newsletter", subtitle: "Stats, story, tip, pick, CTA—monthly." },
    { match: "Past-Client Care Calendar", title: "Care for Past Clients", subtitle: "Quarterly touches, notes, invites." },
    { match: "Hyperlocal Facebook Group", title: "Grow a Local Group", subtitle: "Rules, weekly topics, promo limits." },
    { match: "Vendor Co-Marketing Kit", title: "Co-Market with Vendors", subtitle: "Shared calendar and co-branded assets." },
    { match: "‘Just Closed’ Story Framework", title: "Tell Winning Stories", subtitle: "Client story → lesson → CTA format." },
  ],

  "Module 10 — Digital Ads & AI Tools": [
    { match: "Landing Page CRO Audit", title: "Fix Your Landing Page", subtitle: "Headline, proof, CTA, friction, speed fixes." },
    { match: "7-Day Follow-Up Sequence", title: "Follow Up That Converts", subtitle: "Day-by-day SMS + email with branches." },
    { match: "No-Show Prevention Flow", title: "Reduce No-Shows", subtitle: "Smart reminders + ‘what to expect’ checklist." },
    { match: "Retargeting Ad Set", title: "Retarget Bouncers", subtitle: "Pain/proof/curiosity angles for bounce-backs." },
    { match: "Site Chatbot Script", title: "Qualify & Book in Chat", subtitle: "Greeting → qualify → offer → booking." },
    { match: "AI Systems Stack", title: "Pick the Right AI Stack", subtitle: "Workflows, tools, integrations, privacy." },
    { match: "Super-Prompt Trio", title: "Use 3 Super-Prompts", subtitle: "Listing Pack, Seller Brief, Negotiation Coach." },
    { match: "AI Usage & Ethics Policy", title: "Ship an AI Policy", subtitle: "Purpose, data, verification, disclosure, fair housing." },
    { match: "Daily AI Briefing Ritual", title: "Daily 10-Min AI Brief", subtitle: "Scan, save, apply, share; 3 daily questions." },
    { match: "AI Market Dashboard Spec", title: "Build an AI Dashboard", subtitle: "Key KPIs + auto-summary + embed plan." },
  ],

  "Module 11 — Automation & Workflows": [
    { match: "AI Automation Blueprint", title: "Map Your Automations", subtitle: "Triggers, actions, time saved, and stack." },
    { match: "Lead Routing + Auto Follow-Up", title: "Route & Auto-Reply Leads", subtitle: "Assign owner, tag, SMS/email, SLA." },
    { match: "Post-Closing Drip (12 Mo.)", title: "12-Month Drip", subtitle: "Monthly topics with personalization fields." },
    { match: "Content Repurposing Flow", title: "Repurpose 1 into 5", subtitle: "Turn 1 long asset into 5 outputs with AI." },
    { match: "Transaction Status Bot", title: "Automate Status Updates", subtitle: "Change triggers client SMS/email templates." },
    { match: "Smart Scheduling Sync", title: "Smarter Scheduling", subtitle: "Calendly ↔ Google ↔ CRM with reminders." },
    { match: "AI Email → Task", title: "Turn Email into Tasks", subtitle: "Auto-classify Gmail → tasks with descriptors." },
    { match: "Weekly Metrics Summary Bot", title: "Weekly Metrics Digest", subtitle: "Leads/showings/offers in Slack/email with graph." },
    { match: "Auto Social Posting", title: "Auto-Post Social", subtitle: "New listing/closing/blog → caption → publish." },
    { match: "‘/delegate’ Task Assistant", title: "Create Tasks Faster", subtitle: "Slash-command expands tasks with GPT." },
  ],

  "Module 12 — Realtor Resources & Intelligence": [
    { match: "Market Data Source Finder", title: "Find Market Data", subtitle: "Top 10 sources/APIs with frequency and use." },
    { match: "Realtor Blog Curator", title: "Follow the Best Blogs", subtitle: "Top 15 blogs with why they matter." },
    { match: "YouTube Channel Radar", title: "Best YouTube Channels", subtitle: "Top 15 channels + key playlists." },
    { match: "Podcast Playbook", title: "Must-Listen Podcasts", subtitle: "Top 15 shows with weekly schedule." },
    { match: "Substack/Newsletter Watchlist", title: "Best Newsletters", subtitle: "Top 10 subs with focus and cadence." },
    { match: "Social Expert Tracker", title: "Who to Follow", subtitle: "Top 20 creators by niche and insight." },
    { match: "Realtor News Portal Guide", title: "Trusted News Sources", subtitle: "10 outlets with bias notes and tips." },
    { match: "Trend Watch Prompt", title: "Spot Emerging Trends", subtitle: "Weekly search + prompt template." },
    { match: "Local Intelligence Dashboard", title: "Build a Local Intel Hub", subtitle: "Permits, zoning, employers, development." },
    { match: "Personal Learning Roadmap (6 mo.)", title: "6-Month Learning Plan", subtitle: "Monthly mix of blogs, pods, YT, newsletters." },
  ],
};