// src/prompts.ts

// Module definitions with 10 prompts each. These replicate the initial 12 modules.
const M1 = [
    {title:"90-Day Inbound Lead Blueprint",quick:"Act as a marketing strategist for [your market - example: Austin, TX]. Build a 90-day plan for [buyer/seller/investor] leads via [your channel - example: Facebook Ads, Instagram Reels, YouTube]. Include weekly calendar, KPIs, 5 hooks, UTMs.", role:"marketing strategist",deliverable:"A 12-week marketing calendar + 5 ready-to-use post ideas + tracking setup",success:"≥15 leads/week by week 6; CPL <$[your target cost per lead]."},
  {title:"YouTube Channel Plan (12 Episodes)",quick:"Design a 12-episode YouTube plan for [your niche - example: first-time buyers, luxury homes, investors] in [your market - example: Austin, TX]: titles, hooks, CTAs, b-roll, keywords. Include upload cadence + thumbnail angles.", role:"content strategist",deliverable:"12 video titles + scripts + thumbnail ideas + keywords for each episode",success:"≥5% CTR; Avg view duration ≥40%."},
  {title:"Local SEO Starter Kit",quick:"Create a local SEO checklist for [your city - example: Austin, TX]: GMB, citations, review cadence, FAQ schema, location pages. Output priorities + timelines.", role:"SEO consultant",deliverable:"Step-by-step checklist to get your Google ranking up",success:"Rank top-3 for [service + city] within 90 days (leading indicators)."},
  {title:"Listing Lead Magnet Funnel",quick:"Draft a 'Home Valuation + Market Update' funnel with landing copy, 3-email nurture, SMS, and retargeting angles.", role:"funnel architect",deliverable:"Landing page copy + 3 follow-up emails + 2 text messages",success:"Opt-in ≥25%; reply ≥15% by Day 7."},
  {title:"Neighborhood Guide Generator",quick:"Produce a neighborhood guide template for [your area - example: South Austin, Tarrytown, Mueller]: lifestyle, schools, commute, pricing, 5 hotspots, map idea.", role:"local content creator",deliverable:"A complete neighborhood guide you can brand and share",success:"Guide downloads ≥50/month."},
  {title:"Open House Promo Pack",quick:"Create pre/during/post open house assets: IG reel script, flyer copy, sign-in CTA, follow-up text/email.", role:"event marketer",deliverable:"Social post scripts + flyer copy + follow-up messages",success:"CRM capture rate ≥30% of visitors."},
  {title:"Referral Engine Email Series",quick:"Write a 4-email referral/introductions series for SOI: value first, social proof, soft ask, reminder.", role:"copywriter",deliverable:"4 emails asking for referrals (the right way)",success:"Reply rate ≥12%; referrals per 100 ≥5."},
  {title:"Instagram Reels Calendar (30 Days)",quick:"Build a 30-day Reels plan: hooks, captions, on-screen beats, CTAs. Balance education/story/listings.", role:"short-form coach",deliverable:"30 days of Instagram Reel ideas with captions",success:"3 posts/week; avg reach ↑ 50% in 30 days."},
  {title:"Brand Positioning Statement",quick:"Craft a unique positioning + tagline for [your niche - example: first-time buyers, luxury condos, investors] in [your market - example: Austin, TX] with proof points and voice guide.", role:"brand strategist",deliverable:"Your unique tagline + 3 reasons why clients should choose you",success:"Message used consistently across site/social."},
  {title:"Review & Social Proof System",quick:"Design a post-closing review capture flow: ask script, links, reminder cadence, showcase placements.", role:"reputation manager",deliverable:"Scripts + reminders + plan to get more 5-star reviews",success:"≥70% of closed clients leave a review."},
  {title:"YouTube Channel Plan (12 Episodes)",quick:"Design a 12-episode YouTube plan for [your niche - example: first-time buyers, luxury homes, investors] in [your market - example: Austin, TX]: titles, hooks, CTAs, b-roll, keywords. Include upload cadence + thumbnail angles.", role:"content strategist",deliverable:"Table: Ep | Title | Hook | CTA | Keyword | B-roll | Thumbnail idea.",success:"≥5% CTR; Avg view duration ≥40%."},
  {title:"Local SEO Starter Kit",quick:"Create a local SEO checklist for [your city - example: Austin, TX]: GMB, citations, review cadence, FAQ schema, location pages. Output priorities + timelines.", role:"SEO consultant",deliverable:"Checklist with High/Med/Low impact + owner + deadline.",success:"Rank top-3 for [service + city] within 90 days (leading indicators)."},
  {title:"Listing Lead Magnet Funnel",quick:"Draft a ‘Home Valuation + Market Update’ funnel with landing copy, 3-email nurture, SMS, and retargeting angles.", role:"funnel architect",deliverable:"Page wireframe + copy + 3 emails + 2 SMS + 3 retargeting hooks.",success:"Opt-in ≥25%; reply ≥15% by Day 7."},
  {title:"Neighborhood Guide Generator",quick:"Produce a neighborhood guide template for [your area - example: South Austin, Tarrytown, Mueller]: lifestyle, schools, commute, pricing, 5 hotspots, map idea.", role:"local content creator",deliverable:"PDF outline + blog outline + social carousel notes.",success:"Guide downloads ≥50/month."},
  {title:"Open House Promo Pack",quick:"Create pre/during/post open house assets: IG reel script, flyer copy, sign-in CTA, follow-up text/email.", role:"event marketer",deliverable:"Run-of-show + assets + follow-up sequence.",success:"CRM capture rate ≥30% of visitors."},
  {title:"Referral Engine Email Series",quick:"Write a 4-email referral/introductions series for SOI: value first, social proof, soft ask, reminder.", role:"copywriter",deliverable:"4 emails + subject lines + cadence.",success:"Reply rate ≥12%; referrals per 100 ≥5."},
  {title:"Instagram Reels Calendar (30 Days)",quick:"Build a 30-day Reels plan: hooks, captions, on-screen beats, CTAs. Balance education/story/listings.", role:"short-form coach",deliverable:"Table: Day | Idea | Hook | Caption | CTA.",success:"3 posts/week; avg reach ↑ 50% in 30 days."},
  {title:"Brand Positioning Statement",quick:"Craft a unique positioning + tagline for [your niche - example: first-time buyers, luxury homes, investors] in [your market - example: Austin, TX] with proof points and voice guide.", role:"brand strategist",deliverable:"1-liner + 3 proof bullets + tone/style notes.",success:"Message used consistently across site/social."},
  {title:"Review & Social Proof System",quick:"Design a post-closing review capture flow: ask script, links, reminder cadence, showcase placements.", role:"reputation manager",deliverable:"Templates + reminder SOP + showcase widgets.",success:"≥70% of closed clients leave a review."}
];

const M2 = [
  {title:"Weekly Productivity Audit",quick:"Audit calendar/tasks for a team of [number of agents on your team - example: 3, 5, 10] in [your market - example: Austin, TX]. Table: Task | Time | ROI | Automate/Delegate/Delete | Tool.",role:"productivity coach",deliverable:"A breakdown of what to stop doing, automate, or delegate",success:"Reclaim ≥5 hours/agent/week."},
  {title:"Daily Checklist Builder",quick:"Create a 12-task daily checklist balancing pipeline/admin/prospecting/learning. Export-friendly.",role:"workflow architect",deliverable:"Your daily to-do list (morning, afternoon, evening)",success:"≥80% daily completion."},
  {title:"Pipeline SOP (Lead→Close)",quick:"Define CRM stages, entry/exit criteria, tasks, SLAs, and 2 automations/stage.",role:"contact database consultant",deliverable:"Step-by-step process from lead to closed deal",success:"response time compliance ≥95%."},
  {title:"Listing Launch Timeline (T-14→T+14)",quick:"Create a listing launch Gantt with owners, assets, dependencies, compliance checks.",role:"project manager",deliverable:"28-day timeline showing what to do and when",success:"0 missed disclosures; on-time go-live."},
  {title:"Buyer Onboarding Journey",quick:"Map onboarding for [your buyer type - example: first-time buyers under 35, downsizers, investors]: welcome pack, expectations, template updates.",role:"CX designer",deliverable:"Welcome email + what to send buyers on day 1, 7, 14",success:"Buyer satisfaction score ≥9/10."},
  {title:"Vendor Directory Framework",quick:"Sheet structure for lenders/inspectors/trades with verification cadence and disclaimers.",role:"ops manager",deliverable:"Spreadsheet template to organize your vendors",success:"Quarterly verification 100%."},
  {title:"File Naming & Docs Policy",quick:"Create naming convention + folder tree + retention schedule for [your cloud storage - example: Google Drive, Dropbox, OneDrive].",role:"compliance officer",deliverable:"Simple system to name and organize your files",success:"Doc retrieval <2 minutes."},
  {title:"Inbox & DM Triage SOP",quick:"Multi-channel response time + templates + escalation path; rules for auto-labels/tasks.",role:"communication lead",deliverable:"Rules for responding to emails and DMs fast",success:"Avg response <15 min; 0 missed leads."},
  {title:"Post-Closing Handoff Process",quick:"Checklist to TC: survey, review ask, gift, anniversary automation.",role:"transaction coordinator",deliverable:"Post-close checklist (survey, gift, review request)",success:"100% clients enter nurture."},
  {title:"One-Page Operating System",quick:"Create a 1-pager: Vision, 90-day goals, goal metrics, meeting rhythm, org chart.",role:"business coach",deliverable:"Your business on one page (goals, metrics, meetings)",success:"<30 min weekly meeting, goal metric alignment."}
];

const M3 = [
  {title:"GCI Reverse-Engineering",quick:"Turn GCI [your budget in dollars - example: $3000, $5000] and avg side [your target amount in dollars] into weekly activity targets using conversion rates.",role:"performance coach",deliverable:"Exact number of calls and appointments you need each week",success:"Exact # calls/appts to hit target."},
  {title:"Weekly Scorecard",quick:"Scorecard for leading/lagging: calls, contacts, appts, contracts, posts.",role:"ops analyst",deliverable:"One-page scorecard to track your weekly numbers",success:"Update in <5 min weekly."},
  {title:"Prospecting Habit Protocol",quick:"Build a 20-min daily ritual for [your prospecting method - example: door knocking, cold calling, social media DMs]: trigger→routine→reward.",role:"behavioral coach",deliverable:"Simple daily routine to build a prospecting habit",success:"≥5 new contacts/day × 21 days."},
  {title:"Weekly Reflection Template",quick:"One-page review: wins, numbers, blockers, experiments, focus.",role:"growth mentor",deliverable:"Weekly check-in template (wins, numbers, what to fix)",success:"Consistent self-reporting trends."},
  {title:"30-Day Skill Sprint",quick:"Design a 30-day sprint for [the skill you want to master - example: cold calling, social media, negotiations]: daily drills + checkpoints.",role:"training manager",deliverable:"30-day plan to master one skill (with daily practice)",success:"≥20% competence gain."},
  {title:"Goal Red-Team Exercise",quick:"List reasons you might miss [your specific goal - example: 50 transactions, $250K GCI, 100 new clients] + mitigation plan.",role:"strategic coach",deliverable:"What could go wrong with your goal + how to prevent it",success:"2 preventions implemented now."},
  {title:"Accountability Partner Rules",quick:"Create a 15-min weekly accountability agenda + commitment contract.",role:"team coach",deliverable:"Weekly check-in agenda for you and your accountability partner",success:"≥80% completion in 4 weeks."},
  {title:"Personal P&L Dashboard",quick:"Agent P&L: income, taxes, savings, investments; alerts <40% margin.",role:"financial coach",deliverable:"Simple profit tracker (what you make vs. what you keep)",success:"Know net profit weekly."},
  {title:"Morning Priming Prompts",quick:"3-min exercise: affirmation, visualization, gratitude, micro-goal.",role:"mindset coach",deliverable:"3-minute morning routine to start your day right",success:"Mood/energy ≥8/10 after 7 days."},
  {title:"End-of-Day Debrief",quick:"Nightly check-in: what mattered, improvements, top win; auto-log.",role:"reflection facilitator",deliverable:"Quick end-of-day journal prompts (3 questions)",success:"≥70% completion in 30 days."}
];

const M4 = [
  {title:"Pricing Strategy Script",quick:"Price talk track with comps, DOM, trends; analogy→data→position→CTA.",role:"listing-presentation coach",deliverable:"Script to explain pricing to sellers (with market data)",success:"Seller accepts within 5%."},
  {title:"Commission Value Conversation",quick:"Handle ‘lower your commission’: acknowledge→value reframe→choice close.",role:"negotiation coach",deliverable:"How to respond when sellers ask you to lower your fee",success:"≥70% full fee retention."},
  {title:"FSBO Conversion Sequence",quick:"3 calls + 3 texts for FSBO with [their motivation and timeline - example: divorce, need to sell in 60 days]; compliant phrasing.",role:"lead-conversion specialist",deliverable:"Call and text scripts to convert for-sale-by-owner sellers",success:"≥20% appointment rate."},
  {title:"Competing Agent Response",quick:"Acknowledge multi-agent interviews; differentiate→proof→low-risk CTA.",role:"persuasion coach",deliverable:"What to say when sellers are interviewing other agents",success:"≥50% signed listing."},
  {title:"Rate-Sensitivity Buyer Talk",quick:"Explain payment impact; discuss buy-downs/refi-later with disclaimer.",role:"mortgage conversationalist",deliverable:"How to talk to buyers worried about interest rates",success:"≥70% remain active."},
  {title:"Multiple-Offer Strategy",quick:"Buyer plan: prep, terms, escalation, appraisal gap, debrief.",role:"buyer strategist",deliverable:"Strategy for winning in multiple-offer situations",success:"Win rate ≥60% multi-offer."},
  {title:"Buyer Consult Deck Outline",quick:"Slide outline: process, timeline, stats, agency, next steps.",role:"training designer",deliverable:"Slide outline for your buyer consultation meeting",success:"≥90% to signed agency."},
  {title:"Listing Refresh Plan",quick:"At Day [your timeline or number - be specific] low activity: reshoot, recopy, retarget, reprice, relaunch.",role:"marketing consultant",deliverable:"Plan to revive a stale listing (new photos, price, ads)",success:"Showings ↑ ≥30% in 7 days."},
  {title:"Graceful Disengagement Scripts",quick:"5 ways to exit misaligned clients while preserving goodwill.",role:"relationship strategist",deliverable:"5 polite ways to fire a difficult client",success:"Positive reviews maintained."},
  {title:"Repair Request Negotiation",quick:"Matrix for inspection items; fix/credit/price + sample email.",role:"contract coach",deliverable:"How to negotiate repairs after inspection",success:"≥80% accepted w/o large cuts."}
];

const M5 = [
  {title:"White-Glove Onboarding",quick:"3 touches in 72h: welcome, next-7-days checklist, FAQ video.",role:"CX designer",deliverable:"Welcome email + 7-day checklist + FAQ video for new clients",success:"Week-1 CSAT ≥9/10."},
  {title:"Weekly Update Cadence",quick:"Email + text summary + CRM log: progress, next steps, key dates.",role:"communications strategist",deliverable:"Weekly update template (progress, next steps, key dates)",success:"0 status-check inquiries."},
  {title:"Bad-News Playbook",quick:"Scripts for appraisal shortfall/inspection issues: acknowledge→facts→options→next step.",role:"crisis comms coach",deliverable:"Scripts for delivering bad news (appraisal low, inspection issues)",success:"≥90% stay engaged."},
  {title:"Move-Day Concierge",quick:"Checklist: utilities, vendors, locksmith, mail, welcome kit + 7/30/90 surveys.",role:"service planner",deliverable:"Moving day checklist + welcome kit + follow-up surveys",success:"≥80% survey response; ≥1 referral in 6 mo."},
  {title:"Expectations Agreement",quick:"Agreement: communication hours, response times, decision rights.",role:"client-relations consultant",deliverable:"Client agreement (communication hours, response times)",success:"0 major comms breakdowns."},
  {title:"Year-1 Maintenance Series",quick:"Quarterly maintenance emails for [property/climate] + vendor CTAs.",role:"nurture specialist",deliverable:"4 seasonal maintenance emails for homeowners",success:"Open ≥40%; click ≥10%."},
  {title:"Vendor Issue Escalation",quick:"Flow: client→agent→vendor→broker→legal; logging + timeline.",role:"risk manager",deliverable:"Process when vendors mess up (who to contact, timeline)",success:"Ack <24h; resolve <72h."},
  {title:"Surprise & Delight Moments",quick:"5 touchpoints by milestone with budget $[your timeline or number - be specific] and personalization.",role:"retention strategist",deliverable:"5 gift ideas for client milestones",success:"Referrals ↑ ≥20% YoY."},
  {title:"Service Recovery Templates",quick:"Apology|Accountability|Remedy|Re-commit|Follow-up + public-review reply.",role:"reputation consultant",deliverable:"Apology templates + how to fix client complaints",success:"Complaints closed; ≥4★ avg."},
  {title:"Closing-Day Story Pack",quick:"Shot list, captions, hashtags, review ask + compliance note.",role:"social content coach",deliverable:"Shot list + captions + hashtags for closing day posts",success:"≥70% clients post/tag in 24h."}
];

const M6 = [
  {title:"12-Month Cashflow Model",quick:"Forecast income/expenses with tax, reserves, profit targets; monthly table.",role:"finance coach",deliverable:"Monthly income and expense tracker",success:"Know runway & savings by month 12."},
  {title:"Marketing Budget Allocator",quick:"Distribute $[your timeline or number - be specific]/mo across [your marketing channels - example: Facebook Ads, Google Ads, Zillow, direct mail]; CPL targets; scale/cut rules.",role:"marketing CFO",deliverable:"How to split your marketing budget across channels",success:"≤$[Y] CPL; ≥20% ROI/channel."},
  {title:"Profitability Review Audit",quick:"Analyze expenses by ROI; keep/cut/renegotiate + 90-day savings plan.",role:"business consultant",deliverable:"Which expenses to cut + 90-day savings plan",success:"Reduce expenses ≥15%."},
  {title:"Commission Advance Tree",quick:"Decision framework: cashflow, deal certainty, cost, alternatives.",role:"risk advisor",deliverable:"When to take a commission advance (decision tree)",success:"0 unnecessary advances."},
  {title:"Team Compensation Plan",quick:"Comp for ISA/LA/TC: base/split/bonus/cap + retention incentives.",role:"comp architect",deliverable:"Pay structure for assistants and coordinators",success:"Turnover <10% annually."},
  {title:"Quarterly Tax Planning",quick:"Checklist: estimates, deductions log, retirement, receipts; reminders.",role:"tax strategy coach",deliverable:"Tax checklist + deductions + quarterly payment reminders",success:"100% on-time payments."},
  {title:"Investor Service Line",quick:"Offering for investors: criteria, underwriting sheet, fees, deck.",role:"business developer",deliverable:"Service offering for real estate investors",success:"Launch in ≤45 days."},
  {title:"Market Analytics Template",quick:"Dashboard: SP/LP, DOM, MOI for [submarket/type] with talking points.",role:"data analyst",deliverable:"Market stats dashboard with talking points",success:"Monthly update informs listings."},
  {title:"Vendor RFP Generator",quick:"RFP template: scope, deliverables, metrics, pricing, rubric.",role:"procurement advisor",deliverable:"Request for proposal template for vendors",success:"Clarity pre-contract."},
  {title:"Insurance & Risk Checklist",quick:"Policies: E&O, cyber, GL, data; renewal dates; claims protocol.",role:"risk manager",deliverable:"Insurance policies you need + renewal tracker",success:"0 coverage gaps; on-time renewals."}
];

const M7 = [
  {title:"BATNA Power Map",quick:"Build BATNA table for [your situation - example: appraisal came in $15k low, buyer wants seller credits, multiple offers]; include risk check.",role:"negotiation coach",deliverable:"Backup options if this deal falls through",success:"≥2 creative options + thresholds."},
  {title:"Concession Strategy Ladder",quick:"Rank tradeables by cost to client vs value to other party.",role:"deal architect",deliverable:"What to give up and what to ask for in return",success:"≥50% concessions offset."},
  {title:"Anchoring Language Framework",quick:"3 anchors: data-first, emotional story, bracketed range; phrases to avoid.",role:"persuasive linguist",deliverable:"How to set price expectations with words",success:"Offers land within 3% target."},
  {title:"Calibrated Question Builder",quick:"10 ‘how/what’ questions + labels to uncover constraints.",role:"Voss-style trainer",deliverable:"10 questions to uncover what the other side really wants",success:"≥50% more info disclosed."},
  {title:"Appraisal Gap Plan",quick:"If appraisal < offer by [your budget in dollars - example: $3000, $5000]: rebuttal, reprice, bridge cash, renegotiate, cancel.",role:"transaction strategist",deliverable:"What to do when appraisal comes in low",success:"≥70% resolved w/o cancel."},
  {title:"Inspection Resolution Matrix",quick:"Minor/major matrix: repair/credit/ignore with suggested language.",role:"mediator",deliverable:"How to handle inspection items (repair, credit, or ignore)",success:"≥90% resolution in 3 days."},
  {title:"Deadline Pressure Playbook",quick:"Resist TILI deadlines: scripts, alternatives, reframes; pre-deadline checklist.",role:"time-based tactician",deliverable:"How to handle artificial deadlines",success:"0 rushed concessions."},
  {title:"Deal Rescue Protocol",quick:"Save deals with financing/inspection/cold-feet issues; flow + scripts.",role:"conflict specialist",deliverable:"How to save deals that are falling apart",success:"≥60% revived."},
  {title:"Multiple-Offer Ethics Guide",quick:"Ethical handling in [your state or brokerage - example: Texas, Keller Williams]: disclosure, offer mgmt, scripts.",role:"compliance advisor",deliverable:"How to handle multiple offers ethically and legally",success:"100% compliance; 0 complaints."},
  {title:"Negotiation Post-Mortem",quick:"Debrief: what worked, surprises, missed clues, system change; rubric.",role:"reflective coach",deliverable:"Review template after each negotiation",success:"Complete within 48h of close."}
];

const M8 = [
  {title:"Needs-Match Matrix",quick:"Must-have vs nice-to-have matrix for [your target client - example: first-time buyers, move-up buyers, downsizers] in [your market - example: Austin, TX] with commute band [X–Y].",role:"profiling strategist",deliverable:"Weighted table with fit scores.",success:"≥3 neighborhoods fit ≥80%."},
  {title:"Smart Search Strings",quick:"MLS/portal boolean strings + alerts for [criteria] across MLS/Zillow/Redfin.",role:"portal power-user",deliverable:"Search filters to find exactly what buyers want",success:"≤3 irrelevant listings/week."},
  {title:"Off-Market Outreach",quick:"Letter/email/text for [your target area and property type - example: single-family homes in Westlake]; compliant; opt-out line.",role:"listing acquisition specialist",deliverable:"Letters and emails to find off-market properties",success:"≥5% response / 100 sends."},
  {title:"New-Build vs Resale",quick:"Side-by-side with lifecycle cost + agent talking points.",role:"buyer educator",deliverable:"Side-by-side comparison for buyers",success:"Client chooses confidently."},
  {title:"Lender Options Explainer",quick:"Compare lenders/programs for [credit/income profile] with pros/cons.",role:"financing translator",deliverable:"How to compare lenders and loan programs",success:"Select 2 qualified options in 48h."},
  {title:"Investor Deal Screener",quick:"Quick screen for [your investment strategy - example: fix-and-flip, buy-and-hold, BRRRR]: cap rate, cash-on-cash, DSCR estimates.",role:"underwriting coach",deliverable:"Quick calculator for investment properties",success:"Shortlist in under 10 minutes."},
  {title:"Relocation Brief",quick:"Relocation pack: schools, commute, rents vs buys, neighborhoods.",role:"relocation advisor",deliverable:"Welcome pack for buyers moving to your area",success:"Client shortlists 3 areas."},
  {title:"School-Zone Navigator",quick:"Map search + school ratings + taxes for [family profile].",role:"family move strategist",deliverable:"How to search by school ratings and zones",success:"Confidence in top 2 zones."},
  {title:"Downsizer Options Map",quick:"Condos/townhomes w/ accessibility, HOA insights, budgets.",role:"downsizing consultant",deliverable:"Condo and townhome options for downsizers",success:"Tour list within 48h."},
  {title:"First-Time Buyer Roadmap",quick:"From pre-approval to close with expectation management scripts.",role:"first-time coach",deliverable:"Step-by-step timeline from pre-approval to closing",success:"On-track milestones each week."}
];

const M9 = [
  {title:"12-Touch Sphere Plan",quick:"Monthly plan for SOI/past clients/vendors with channel + theme + CTA.",role:"retention strategist",deliverable:"Monthly outreach plan for past clients and sphere",success:"≥30% engagement/touch."},
  {title:"Home-Anniversary Automation",quick:"CRM workflow: reminder→gift tier [$25/$50/$100]→message→social post.",role:"automation expert",deliverable:"Automated anniversary messages + gift tiers",success:"≥95% anniversaries auto-celebrated."},
  {title:"Community Spotlight Series",quick:"12-episode plan on local businesses/nonprofits/events in [your target neighborhood - example: Tarrytown, Hyde Park, Westlake].",role:"local content creator",deliverable:"12 posts featuring local businesses",success:"+25% local followers; 3 collabs."},
  {title:"Client-Appreciation Event",quick:"Plan for [season/theme]: timeline, vendors, sponsors, RSVP.",role:"event marketer",deliverable:"Event planning checklist (venue, vendors, invites)",success:"≥60% attendance; ≥3 referrals."},
  {title:"Review-to-Referral Bridge",quick:"Turn 5★ reviews into warm referral asks (text/email/DM).",role:"relationship copywriter",deliverable:"How to turn 5-star reviews into referral requests",success:"≥20% provide a referral in 30 days."},
  {title:"Newsletter Engine",quick:"Monthly template: market stat, story, tip, local pick, CTA.",role:"newsletter editor",deliverable:"Monthly newsletter template (market stats + tips + local picks)",success:"Open ≥35%, click ≥6%."},
  {title:"Past-Client Care Calendar",quick:"Quarterly touches: maintenance notes, check-ins, invites.",role:"client care planner",deliverable:"Quarterly check-ins for past clients",success:"Retention/referrals up YoY."},
  {title:"Hyperlocal Facebook Group",quick:"Start/moderate a local group: rules, weekly topics, promo limits.",role:"community manager",deliverable:"How to start and grow a neighborhood Facebook group",success:"1000 members in 6 mo."},
  {title:"Vendor Co-Marketing Kit",quick:"Co-marketing SOP with lenders/contractors; shared content calendar.",role:"partnership lead",deliverable:"Co-marketing plan with lenders and contractors",success:"2 co-branded assets/month."},
  {title:"‘Just Closed’ Story Framework",quick:"Client story → lesson → CTA format for posts and emails.",role:"story coach",success:"Save/share rate ↑ 25%."}
];

const M10 = [
  {title:"Landing Page CRO Audit",quick:"Audit [your website URL - example: https://yourdomain.com/home-valuation]: headline, proof, CTA, friction, load/mobile; give fixes + examples.",role:"CRO expert",deliverable:"What's wrong with your landing page + how to fix it",success:"Conv ↑ ≥30% in 14 days."},
  {title:"7-Day Follow-Up Sequence",quick:"SMS+Email for [lead source - example: Facebook ad, Zillow, referral, open house]: Day-by-day copy with branches.",role:"sales automation copywriter",deliverable:"Day-by-day email and text templates for new leads",success:"≥25% reply in 7 days."},
  {title:"No-Show Prevention Flow",quick:"Booking → 24h → 1h reminders + ‘what to expect’ checklist.",role:"workflow optimizer",deliverable:"Automated reminders to reduce no-shows",success:"No-shows <10%."},
  {title:"Retargeting Ad Set",quick:"3 ad angles (pain/proof/curiosity) for visitors who bounced on [page].",role:"digital ad strategist",deliverable:"3 Facebook ads for people who visited your site",success:"Re-engagement CTR ≥15%."},
  {title:"Site Chatbot Script",quick:"Qualify and book leads: greeting→qualify→offer→booking→CRM tags.",role:"AI convo designer",deliverable:"Chatbot conversation flow to qualify and book leads",success:"Chat→lead ≥25%."},
  {title:"AI Systems Stack",quick:"Design AI stack for [number of people on your team - example: 2, 5, 10 agents]: workflows, tools, integration notes, privacy.",role:"tech architect",deliverable:"Which AI tools to use and how to connect them",success:"Admin time −30%/week."},
  {title:"Super-Prompt Trio",quick:"3 super-prompts: Listing Pack, Seller Brief, Negotiation Coach.",role:"prompt engineer",deliverable:"3 powerful prompts you'll use every day",success:"10× output speed & consistency."},
  {title:"AI Usage & Ethics Policy",quick:"Policy for [your brokerage name - example: RE/MAX, Keller Williams, eXp Realty]: purpose, use, data, verification, disclosure, fair housing.",role:"compliance strategist",deliverable:"Policy for using AI ethically in your business",success:"100% agent compliance."},
  {title:"Daily AI Briefing Ritual",quick:"10-min habit: scan sources, save, apply, share; 3 daily questions.",role:"learning coach",deliverable:"10-minute daily habit to stay current on AI",success:"30-day habit formed."},
  {title:"AI Market Dashboard Spec",quick:"KPIs (New Listings, DOM, MOI, SP/LP, $/sqft) + auto-summary + CSV/Notion embed.",role:"product designer",deliverable:"Automated market report dashboard",success:"Used daily for client reports."}
];

const M11 = [
  {title:"AI Automation Blueprint",quick:"Map automations for [number of people on your team - example: 2, 5, 10 agents] with [the tools you currently use - example: Follow Up Boss, Canva, Google Workspace, Calendly]; triggers, actions, time saved.",role:"AI systems architect",deliverable:"Map of all automations for your business",success:"≥10 hrs saved/agent/week."},
  {title:"Lead Routing + Auto Follow-Up",quick:"Source→CRM→owner assign→SMS/email→task; include tags and SLA.",role:"CRM automation consultant",deliverable:"Automated lead assignment and follow-up",success:"100% leads replied <5 min."},
  {title:"Post-Closing Drip (12 Mo.)",quick:"Design 12-month nurture: monthly topic + personalization fields.",role:"retention automation designer",deliverable:"12-month automated email sequence for past clients",success:"≥25% repeat/referral in 12 mo."},
  {title:"Content Repurposing Flow",quick:"Turn 1 long video/blog into 5 assets via AI + schedulers.",role:"content systems engineer",deliverable:"Turn 1 video into 5 social posts automatically",success:"5× outputs in <30 min."},
  {title:"Transaction Status Bot",quick:"Status change → templated client updates via SMS/email.",role:"workflow developer",deliverable:"Automated status updates for clients",success:"0 ‘what’s next?’ messages."},
  {title:"Smart Scheduling Sync",quick:"Calendly↔Google↔CRM; reminders + logging; double-book prevention.",role:"calendar workflow designer",deliverable:"Connect your calendar to your contact database",success:"No-shows <5%."},
  {title:"AI Email → Task",quick:"Classify Gmail → create tasks in Todoist/Notion with GPT descriptors.",role:"productivity consultant",deliverable:"Automatically create tasks from emails",success:"100% inbox triage automated."},
  {title:"Weekly Metrics Summary Bot",quick:"Compile leads/showings/offers into Slack/email with graph.",role:"data-reporting specialist",deliverable:"Automated weekly stats email",success:"100% team awareness weekly."},
  {title:"Auto Social Posting",quick:"New listing/closing/blog → caption via AI → publish → log.",role:"marketing automation expert",deliverable:"Automatically post new listings to social media",success:"≥3 posts/week automated."},
  {title:"‘/delegate’ Task Assistant",quick:"Slash-command creates detailed tasks with GPT expansion.",role:"VA workflow designer",success:"−80% manual task entry time."}
];

const M12 = [
  {title:"Market Data Source Finder",quick:"Top 10 data/report/API sources for [national/state/city] stats; frequency + use case.",role:"data researcher",deliverable:"Top 10 sources for market data and stats",success:"Updated data weekly."},
  {title:"Realtor Blog Curator",quick:"Top 15 blogs for real estate/marketing/AI; why valuable + frequency.",role:"content scout",deliverable:"15 best blogs for real estate agents",success:"15-min/day reading routine."},
  {title:"YouTube Channel Radar",quick:"Top 15 channels for sales/AI/branding/tech; best playlists.",role:"media analyst",deliverable:"15 best YouTube channels for agents",success:"Curate 3 videos/week."},
  {title:"Podcast Playbook",quick:"Top 15 podcasts; theme, length, why listen; weekly schedule.",role:"learning strategist",deliverable:"15 best podcasts for real estate professionals",success:"Daily 1-episode habit."},
  {title:"Substack/Newsletter Watchlist",quick:"10 must-subscribe AI+RE newsletters; focus + frequency + value.",role:"knowledge curator",deliverable:"10 must-read newsletters",success:"Weekly insight pipeline."},
  {title:"Social Expert Tracker",quick:"Top 20 LinkedIn/X/IG/TikTok accounts; niche + notable insights.",role:"social intel researcher",deliverable:"20 experts to follow on social media",success:"Comment weekly on 3 posts."},
  {title:"Realtor News Portal Guide",quick:"10 news outlets for housing/policy/tech; bias/slant + usage tips.",role:"news curator",deliverable:"10 news sources for housing and policy",success:"Daily briefing workflow."},
  {title:"Trend Watch Prompt",quick:"Weekly search/prompt template to find emerging AI/housing trends.",role:"trend analyst",deliverable:"Weekly prompt to discover emerging trends",success:"Monday 9am ritual in place."},
  {title:"Local Intelligence Dashboard",quick:"Template aggregating permits, zoning, dev, employers for [city/county].",role:"hyperlocal researcher",deliverable:"Track local development and economic data",success:"1-page local insights hub."},
  {title:"Personal Learning Roadmap (6 mo.)",quick:"Month-by-month plan mixing blogs, podcasts, YouTube, newsletters, AI practice.",role:"learning architect",deliverable:"6-month learning plan (what to read, watch, practice)",success:"+10% efficiency or GCI in 6 mo."}
];

// Final export: array of module arrays
export const prompts = [M1, M2, M3, M4, M5, M6, M7, M8, M9, M10, M11, M12];